---
# Pre-check: Determine if container is already running
- name: Include pre-check tasks
  ansible.builtin.include_tasks: precheck.yml

# Run the creation task
- name: Include create tasks
  ansible.builtin.include_tasks: create.yml

# Wait until the container is properly registered
- name: Include wait tasks
  ansible.builtin.include_tasks: wait.yml

# Start the container
- name: Include start tasks
  ansible.builtin.include_tasks: start.yml
