---
- name: Check if the container is already running
  ansible.builtin.command: >
    {{ role_path }}/files/check_container_running.py
    --host "{{ proxmox_api_host }}"
    --user "{{ proxmox_api_user }}"
    --token_name "{{ proxmox_api_id | default('') }}"
    --token_value "{{ proxmox_api_secret | default('') }}"
    --password "{{ proxmox_api_password | default('') }}"
    --node "{{ proxmox_node }}"
    --vmid "{{ container.vmid }}"
  delegate_to: localhost
  register: proxmox_provision_container_status
  changed_when: false
  ignore_errors: true

- name: Set fact whether container is running
  ansible.builtin.set_fact:
    proxmox_provision_container_already_running: "{{ proxmox_provision_container_status.rc == 0 }}"
