---
- name: Check if the container is already running
  command: >
    {{ role_path }}/files/check_container_running.py
    --host "{{ proxmox_api_host }}"
    --user "{{ proxmox_api_user }}"
    --token_name "{{ proxmox_api_id }}"
    --token_value "{{ proxmox_api_secret }}"
    --node "{{ proxmox_node }}"
    --vmid "{{ container.vmid }}"
  delegate_to: localhost
  register: container_status
  ignore_errors: yes

- name: Set fact whether container is running
  set_fact:
    container_already_running: "{{ container_status.rc == 0 }}"
