---
- name: Ensure LXC container is started on Proxmox
  community.proxmox.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_secret | default(omit) }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ container.vmid }}"
    state: started
  register: proxmox_provision_start_result
  failed_when: proxmox_provision_start_result.failed and ('already running' not in proxmox_provision_start_result.msg)
  when: not (proxmox_provision_container_already_running | default(false))
