---
- name: Wait for container to be registered with expected hostname
  ansible.builtin.command: >
    {{ role_path }}/files/wait_for_container.py
    --host "{{ proxmox_api_host }}"
    --user "{{ proxmox_api_user }}"
    --token_name "{{ proxmox_api_id | default('') }}"
    --token_value "{{ proxmox_api_secret | default('') }}"
    --password "{{ proxmox_api_password | default('') }}"
    --node "{{ proxmox_node }}"
    --vmid "{{ container.vmid }}"
    --expected-hostname "{{ container.hostname }}"
    --retries 10
    --delay 3
  delegate_to: localhost
  register: container_status
  changed_when: false
  until: container_status.rc == 0
  retries: 10
  delay: 3
  when: not (container_already_running | default(false))
