---
- name: Wait for connection to container
  ansible.builtin.wait_for_connection:
    timeout: 15
  register: root_conn_test
  ignore_errors: true

# - name: Debug - Show container host
#   debug:
#     msg: "Container host is: {{ ansible_host }}"

# - name: Debug - Show container private key file
#   debug:
#     msg: "Container key is: {{ ansible_ssh_private_key_file }}"

# - name: Debug - Show container user
#   debug:
#     msg: "Container user is: {{ ansible_user }}"

# - name: Debug - Show connection check result
#   debug:
#     var: root_conn_test

- name: End play if connection check fails
  ansible.builtin.meta: end_play
  when: root_conn_test.failed
