---
- name: Wait for connection to container
  ansible.builtin.wait_for_connection:
    timeout: 15
  register: container_setup_root_conn_test
  ignore_errors: true

- name: Try non-root user connection if root fails
  ansible.builtin.wait_for_connection:
    timeout: 15
  vars:
    ansible_user: "{{ container.config.username }}"
  register: container_setup_user_conn_test
  ignore_errors: true
  when: container_setup_root_conn_test.failed

- name: Update inventory with non-root user if root failed
  ansible.builtin.add_host:
    name: "{{ inventory_hostname }}"
    groups: proxmox_containers
    ansible_host: "{{ ansible_host }}"
    ansible_connection: ssh
    ansible_user: "{{ container.config.username }}"
    ansible_ssh_private_key_file: "{{ container.config.private_key }}"
    ansible_python_interpreter: /usr/bin/python3
    container: "{{ container }}"
    ansible_become: true
    ansible_become_method: sudo
  when: container_setup_root_conn_test.failed and not container_setup_user_conn_test.failed

- name: End play if both connection attempts fail
  ansible.builtin.meta: end_play
  when: container_setup_root_conn_test.failed and (container_setup_user_conn_test.failed | default(true))
