---
- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  become: true

- name: Ensure sudo is installed
  ansible.builtin.apt:
    name: sudo
    state: present
  become: true

- name: Create non-root user
  ansible.builtin.user:
    name: "{{ container.config.username }}"
    shell: /bin/bash
    create_home: true
    password: "{{ container.config.user_password | password_hash('sha512') }}"
  become: true

- name: Add user to sudo group
  ansible.builtin.user:
    name: "{{ container.config.username }}"
    groups: sudo
    append: true
  become: true

- name: Allow user passwordless sudo
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ container.config.username }}"
    content: "{{ container.config.username }} ALL=(ALL) NOPASSWD: ALL\n"
    owner: root
    group: root
    mode: '0440'
  become: true

- name: Copy SSH public key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ container.config.username }}"
    state: present
    key: "{{ lookup('file', container.pubkey_file) }}"
  become: true

- name: Ensure PubkeyAuthentication is enabled in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
  become: true

- name: Ensure PasswordAuthentication is disabled in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  become: true

- name: Ensure PermitRootLogin is disabled in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  become: true

- name: Restart SSH service
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true
