---
- name: Update apt cache and install extra packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - kitty-terminfo
      - tmux
      - htop
      - curl
      - jq
      - fzf
      - fastfetch
      - gawk
      - make
      - git
    state: present
  become: true
  register: container_extras_apt_result
  notify: Update apt cache

- name: Check if update-motd.d backup exists
  ansible.builtin.stat:
    path: /etc/update-motd.d.bak
  become: true
  register: container_extras_motd_backup_stat

- name: Backup update-motd.d and create new directory
  ansible.builtin.shell: "mv /etc/update-motd.d /etc/update-motd.d.bak && mkdir /etc/update-motd.d"
  become: true
  changed_when: not container_extras_motd_backup_stat.stat.exists

- name: Check motd file size
  ansible.builtin.stat:
    path: /etc/motd
  become: true
  register: container_extras_motd_stat

- name: Truncate /etc/motd
  ansible.builtin.file:
    path: /etc/motd
    state: touch
    mode: '0644'
  become: true
  changed_when: container_extras_motd_stat.stat.size > 0

- name: Check if .hushlogin exists
  ansible.builtin.stat:
    path: "~/.hushlogin"
  become: true
  register: container_extras_hushlogin_stat

- name: Create a .hushlogin file
  ansible.builtin.file:
    path: "~/.hushlogin"
    state: touch
    mode: '0644'
  become: true
  changed_when: not container_extras_hushlogin_stat.stat.exists

- name: Append fastfetch block to .bashrc
  ansible.builtin.blockinfile:
    path: "/home/{{ container.config.username }}/.bashrc"
    marker: "# {mark} FASTFETCH BLOCK"
    block: |
      # Run fastfetch only in interactive shells
      case $- in
          *i*)
              echo " "
              fastfetch
              echo " "
              ;;
          *) ;;  # Do nothing for non-interactive shells
      esac
  become: true
  become_user: "{{ container.config.username }}"

- name: Install ble.sh
  block:
    - name: Clone ble.sh repository
      ansible.builtin.git:
        repo: https://github.com/akinomyoga/ble.sh.git
        dest: "/home/{{ container.config.username }}/ble.sh"
        version: master
        depth: 1
        recursive: true
      become: true
      become_user: "{{ container.config.username }}"

    - name: Install ble.sh
      ansible.builtin.command: "make -C ble.sh install PREFIX=/home/{{ container.config.username }}/.local"
      args:
        chdir: "/home/{{ container.config.username }}"
      become: true
      become_user: "{{ container.config.username }}"
      changed_when: true  # Since make will report its own changes

    - name: Add ble.sh source to .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ container.config.username }}/.bashrc"
        line: "source /home/{{ container.config.username }}/.local/share/blesh/ble.sh"
        state: present
      become: true
      become_user: "{{ container.config.username }}"

    - name: Clean up ble.sh directory
      ansible.builtin.file:
        path: "/home/{{ container.config.username }}/ble.sh"
        state: absent
      become: true
      become_user: "{{ container.config.username }}"
