---
# roles/proxmox_lxc/tasks/compose-setup.yml

# - name: Debug path_to_compose_files value
#   debug:
#     msg: "path_to_compose_files is: {{ path_to_compose_files | default('not defined') }}"

- name: Create docker directory for each container
  file:
    path: "/home/{{ container.username | default('demo') }}/docker/{{ item.key }}"
    state: directory
    mode: '0755'
  loop: "{{ container.docker_containers | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become: yes
  become_user: "{{ container.username | default('demo') }}"

- name: Copy docker compose file for container "{{ item.key }}"
  copy:
    src: "{{ path_to_compose_files }}/{{ item.key }}.yml"
    dest: "/home/{{ container.username | default('demo') }}/docker/{{ item.key }}/docker-compose.yml"
    mode: '0644'
  loop: "{{ container.docker_containers | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become: yes
  become_user: "{{ container.username | default('demo') }}"

- name: Template .env file for container "{{ item.key }}"
  template:
    src: "{{ path_to_compose_files }}/{{ item.key }}.env.j2"
    dest: "/home/{{ container.username | default('demo') }}/docker/{{ item.key }}/.env"
    mode: '0644'
  loop: "{{ container.docker_containers | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become: yes
  become_user: "{{ container.username | default('demo') }}"

- name: Run docker compose up -d in container directory for "{{ item.key }}"
  shell: "docker compose up -d"
  args:
    chdir: "/home/{{ container.username | default('demo') }}/docker/{{ item.key }}"
  loop: "{{ container.docker_containers | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become: yes
  become_user: "{{ container.username | default('demo') }}"
