#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/proxmox_lxc

- name: Run creation tasks if state is present
  include_tasks: create.yml
  when: container.state == 'present'

- name: Run deletion tasks if state is absent
  include_tasks: delete.yml
  when: container.state == 'absent'

- name: Wait for container status if state is started and flag is set
  include_tasks: status.yml
  when: container.state == 'started' and (container.wait_for_status | default(false))

- name: Run start tasks if state is started
  include_tasks: start.yml
  when: container.state == 'started'

- name: Run stop tasks if state is stopped
  include_tasks: stop.yml
  when: container.state == 'stopped'

- name: Retrieve container IP if flag is set
  include_tasks: get_ip.yml
  when: container.get_ip | default(false)

- name: Add container to dynamic inventory if initial_setup is true
  add_host:
    name: "lxc_{{ container.vmid }}"
    groups: proxmox_containers
    ansible_host: "{{ container_ip }}"
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_private_key_file: "{{ container.private_key }}"
    ansible_python_interpreter: /usr/bin/python3
    container: "{{ container }}"
  when: container.initial_setup | default(false) and container.get_ip | default(false)