#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/proxmox_lxc

- name: Run creation tasks if state is present
  include_tasks: create.yml
  when: container.state == 'present'

- name: Run deletion tasks if state is absent
  include_tasks: delete.yml
  when: container.state == 'absent'