---
services:
  gitea:
    image: 'gitea/gitea:latest'
    restart: unless-stopped
    volumes:
      - '/mnt/md/data/gitea:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - .env
    ports:
      - '${PORT_HTTP}:3000'
      - '${PORT_SSH}:22'